kind: Deployment
apiVersion: apps/v1
metadata:
  name: util
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sleep
      annotations:
        sidecar.istio.io/logLevel: debug
    spec:
      restartPolicy: Always
      serviceAccountName: sleep
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 0
      securityContext: {}
      containers:
        - name: sleep
          image: quay.io/sail-dev/curl
          command:
            - /bin/sleep
            - infinity
          resources: {}
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/sleep/tls
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      serviceAccount: sleep
      volumes:
        - name: secret-volume
          secret:
            secretName: sleep-secret
            defaultMode: 420
            optional: true
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate