
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafkacli
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkacli
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafkacli
      annotations:
        sidecar.istio.io/logLevel: debug
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 0
      securityContext: {}
      containers:
        - name: sleep
          image: registry.redhat.io/amq-streams/kafka-40-rhel9@sha256:b5af92487bc591bd2d3e785817f3e70e1050dc71e97964689b4783ca97644f91
          command:
            - /bin/sleep
            - infinity
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate